### ISSUE TITLE
变量格式错误

### ISSUE THREAD

**Issue by typ431127** [lingme/Typora-AliyunOSS-AutoUpload-Shell#1]
host            ="your-oss-host"
bucket          ="your-oss-bucket"
id              ="your-oss-AccessKey ID"
key             ="your-oss-AccessKey Secret Key"
cloudFolder     ="your-oss-folder"
这几个变量不应该带空格，会报错
```
line 5: host: command not found
 6: bucket: command not found
```

**Comment by lingme** [comment]
hello，不好意思，我漏掉了这条 issues，今天才看到， 我是为了格式清晰一点才这样写的readme，好像不小心更新到了sh文件中，我修改一下，谢谢。

**Comment by lingme** [comment]
已经更新好了，再次感谢
